version: "3.7"
services:
    fpm:
        image: php8.2-fpm
        container_name: php-fpm
        build:
            dockerfile: ./Dockerfile
            context: ./
        volumes:
            - ./:/var/www/html
        ports:
            - "80:8000"
        networks:
            - development-network
    db:
      image: mysql
      container_name: database
      environment:
        MYSQL_ROOT_PASSWORD: root123
      ports:
        - "3307:3306"
      networks:
        - development-network

networks:
    development-network:
        driver: bridge
