version: "3.7"
services:
    fpm:
      image: svikramjeet/php7.3
      container_name: php-fpm
      volumes:
        - ./:/var/www/html
      ports: 
        - "8080:8080"
      networks:
        - development-network
    db:
      image: mysql 
      container_name: database
      environment:
        MYSQL_ROOT_PASSWORD: root123
      ports: 
        - "3307:3306"
      networks:
        - development-network

networks:
    development-network:
        driver: bridge